class ProjectConstants:

    COOKING_TIME_MIN_VALUE = 1
    INGREDIENT_AMOUNT_MIN_VALUE = 1
    USER_NAME_MAX_LENGTH = 150
    USER_LASTNAME_MAX_LENGTH = 150
    TAG_NAME_MAX_LENGTH = 64
    TAG_SLUG_MAX_LENGTH = 32
    INGREDIENT_NAME_MAX_LENGTH = 128
    INGREDIENT_MEASUREMENTUNIT_MAX_LENGTH = 64
    RECIPE_NAME_MAX_LENGTH = 256
    PAGE_NUMBER_PAGINATION = 10
