# Generated by Django 3.2.3 on 2024-09-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='if_favorited',
        ),
    ]
